// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package bigarea

import (
	"github.com/olachat/banban_server/cli_mysql_pipeline/index"
	"github.com/olachat/banban_server/cli_mysql_pipeline/tools/batch_importer/common"
	"github.com/olachat/banban_server/common/nsq"
)

// Injectors from wire.go:

func InitNsqHandler(pkColName string, tables []string, idx *index.Index) *common.BatchImportHandler {
	bigareaNsqAdapter := newNsqAdapter(pkColName, tables)
	batchImportUseCase := common.NewBatchImportUseCase(idx, bigareaNsqAdapter)
	batchImportHandler := common.NewHandler(batchImportUseCase, bigareaNsqAdapter)
	return batchImportHandler
}

func InitNsqConsumer(topic nsq.Topic, channle nsq.Channel, h nsq.NsqHandleMessage) *nsq.NsqConsumer {
	nsqConsumer := nsq.NewNsqConsumer(topic, channle, h)
	return nsqConsumer
}
