// Code generated by MockGen. DO NOT EDIT.
// Source: handler.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	nsq "github.com/nsqio/go-nsq"
)

// MockuseCase is a mock of useCase interface.
type MockuseCase struct {
	ctrl     *gomock.Controller
	recorder *MockuseCaseMockRecorder
}

// MockuseCaseMockRecorder is the mock recorder for MockuseCase.
type MockuseCaseMockRecorder struct {
	mock *MockuseCase
}

// NewMockuseCase creates a new mock instance.
func NewMockuseCase(ctrl *gomock.Controller) *MockuseCase {
	mock := &MockuseCase{ctrl: ctrl}
	mock.recorder = &MockuseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockuseCase) EXPECT() *MockuseCaseMockRecorder {
	return m.recorder
}

// Import mocks base method.
func (m *MockuseCase) Import(arg0 []int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Import", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Import indicates an expected call of Import.
func (mr *MockuseCaseMockRecorder) Import(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Import", reflect.TypeOf((*MockuseCase)(nil).Import), arg0)
}

// MockmsgAdapter is a mock of msgAdapter interface.
type MockmsgAdapter struct {
	ctrl     *gomock.Controller
	recorder *MockmsgAdapterMockRecorder
}

// MockmsgAdapterMockRecorder is the mock recorder for MockmsgAdapter.
type MockmsgAdapterMockRecorder struct {
	mock *MockmsgAdapter
}

// NewMockmsgAdapter creates a new mock instance.
func NewMockmsgAdapter(ctrl *gomock.Controller) *MockmsgAdapter {
	mock := &MockmsgAdapter{ctrl: ctrl}
	mock.recorder = &MockmsgAdapterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockmsgAdapter) EXPECT() *MockmsgAdapterMockRecorder {
	return m.recorder
}

// GetIDs mocks base method.
func (m *MockmsgAdapter) GetIDs(arg0 *nsq.Message) ([]int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetIDs", arg0)
	ret0, _ := ret[0].([]int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetIDs indicates an expected call of GetIDs.
func (mr *MockmsgAdapterMockRecorder) GetIDs(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetIDs", reflect.TypeOf((*MockmsgAdapter)(nil).GetIDs), arg0)
}
