// Code generated by MockGen. DO NOT EDIT.
// Source: use_case.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MocktableStorage is a mock of tableStorage interface.
type MocktableStorage struct {
	ctrl     *gomock.Controller
	recorder *MocktableStorageMockRecorder
}

// MocktableStorageMockRecorder is the mock recorder for MocktableStorage.
type MocktableStorageMockRecorder struct {
	mock *MocktableStorage
}

// NewMocktableStorage creates a new mock instance.
func NewMocktableStorage(ctrl *gomock.Controller) *MocktableStorage {
	mock := &MocktableStorage{ctrl: ctrl}
	mock.recorder = &MocktableStorageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MocktableStorage) EXPECT() *MocktableStorageMockRecorder {
	return m.recorder
}

// FindByIDs mocks base method.
func (m *MocktableStorage) FindByIDs(arg0 []int64) ([]map[string]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByIDs", arg0)
	ret0, _ := ret[0].([]map[string]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByIDs indicates an expected call of FindByIDs.
func (mr *MocktableStorageMockRecorder) FindByIDs(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByIDs", reflect.TypeOf((*MocktableStorage)(nil).FindByIDs), arg0)
}

// GetNames mocks base method.
func (m *MocktableStorage) GetNames() []string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetNames")
	ret0, _ := ret[0].([]string)
	return ret0
}

// GetNames indicates an expected call of GetNames.
func (mr *MocktableStorageMockRecorder) GetNames() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetNames", reflect.TypeOf((*MocktableStorage)(nil).GetNames))
}
