// Code generated by MockGen. DO NOT EDIT.
// Source: handler_wrapper.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	nsq "github.com/nsqio/go-nsq"
)

// MockiBatchImportHandler is a mock of iBatchImportHandler interface.
type MockiBatchImportHandler struct {
	ctrl     *gomock.Controller
	recorder *MockiBatchImportHandlerMockRecorder
}

// MockiBatchImportHandlerMockRecorder is the mock recorder for MockiBatchImportHandler.
type MockiBatchImportHandlerMockRecorder struct {
	mock *MockiBatchImportHandler
}

// NewMockiBatchImportHandler creates a new mock instance.
func NewMockiBatchImportHandler(ctrl *gomock.Controller) *MockiBatchImportHandler {
	mock := &MockiBatchImportHandler{ctrl: ctrl}
	mock.recorder = &MockiBatchImportHandlerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockiBatchImportHandler) EXPECT() *MockiBatchImportHandlerMockRecorder {
	return m.recorder
}

// HandleMsg mocks base method.
func (m *MockiBatchImportHandler) HandleMsg(msg *nsq.Message) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HandleMsg", msg)
	ret0, _ := ret[0].(error)
	return ret0
}

// HandleMsg indicates an expected call of HandleMsg.
func (mr *MockiBatchImportHandlerMockRecorder) HandleMsg(msg interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleMsg", reflect.TypeOf((*MockiBatchImportHandler)(nil).HandleMsg), msg)
}
