[program:cli_mysql_pipeline]
command=/opt/cli_mysql_pipeline/cli_mysql_pipeline --env=partystar
directory=/opt/cli_mysql_pipeline
autostart=true
autorestart=true
startretries=3
stdout_logfile=/var/log/cli_mysql_pipeline/app.log
stdout_logfile_maxbytes=100MB
stdout_logfile_backups=10
stderr_logfile=/var/log/cli_mysql_pipeline/app_err.log
environment=GOTRACEBACK=all
