// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package room

import (
	"github.com/olachat/banban_server/cli_mysql_pipeline/index"
	"github.com/olachat/banban_server/cli_mysql_pipeline/tools/batch_importer/common"
	"github.com/olachat/banban_server/common/nsq"
	"github.com/astaxie/beego/orm"
)

// Injectors from wire.go:

func InitNsqConsumer(topic nsq.Topic, channel nsq.Channel, pkColName string, tables []string, sql SQL, idx *index.Index, db orm.Ormer) *nsq.NsqConsumer {
	roomMysqlAdapter := newMysqlAdapter(tables, pkColName, sql, db)
	batchImportUseCase := common.NewBatchImportUseCase(idx, roomMysqlAdapter)
	roomPhpAdapter := newPHPAdapter()
	batchImportHandler := common.NewHandler(batchImportUseCase, roomPhpAdapter)
	nsqConsumer := provideNsqConsumer(topic, channel, batchImportHandler)
	return nsqConsumer
}

// wire.go:

func provideNsqConsumer(
	topic nsq.Topic,
	channel nsq.Channel,
	h *common.BatchImportHandler,
) *nsq.NsqConsumer {
	return nsq.NewNsqConsumer(topic, channel, h.HandleMsg)
}
